apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceclasses.namespice.io
spec:
  group: namespice.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            resources:
              type: array
              items:
                type: object
                x-kubernetes-preserve-unknown-fields: true
  scope: Cluster
  names:
    plural: namespaceclasses
    singular: namespaceclass
    kind: NamespaceClass
    shortNames:
      - nsc