apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaceclasses.namespice.io
spec:
  group: namespice.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            resources:
              type: array
              items:
                type: object
                x-kubernetes-preserve-unknown-fields: true
  scope: Cluster
  names:
    plural: namespaceclasses
    singular: namespaceclass
    kind: NamespaceClass
    shortNames:
      - nsc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespice-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespice-controller
rules:
  # TODO: this is terrible for security, use namespaced roles instead
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespice-controller-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: namespice-controller
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: namespice-controller
    namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  name: namespice-controller
  namespace: kube-system
spec:
  serviceAccountName: namespice-controller
  containers:
    - name: controller
      image: notfromstatefarm/namespice:latest
      imagePullPolicy: Always